# Generated by Django 4.1.7 on 2023-04-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='exp_before',
            field=models.IntegerField(verbose_name='Стаж до'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='exp_from',
            field=models.IntegerField(verbose_name='Стаж от'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='profession',
            field=models.CharField(choices=[('DEVELOPMENT', 'Разработка'), ('DATASCIENCE', 'Наука о данных'), ('DATAENGINEER', 'Инженер данных'), ('DEVOPS', 'DevOps'), ('TESTER', 'Тестировщик'), ('OTHER', 'Другое')], default='OTHER', max_length=30, verbose_name='Сфера деятельности'),
        ),
    ]
