# Generated by Django 4.1.7 on 2023-04-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
