# Generated by Django 4.1.7 on 2023-04-17 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cv_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_place', models.CharField(max_length=500, verbose_name='Место работы')),
                ('job_exp', models.FloatField(verbose_name='Стаж')),
                ('job_position', models.CharField(max_length=500, verbose_name='Должность')),
                ('job_description', models.TextField(max_length=3000, verbose_name='Обязанности')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_exp', to='cv.cv', verbose_name='Резюме')),
            ],
        ),
    ]
