# Generated by Django 4.1.7 on 2023-04-17 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv', '0003_jobexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobexperience',
            name='cv',
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_exp', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель'),
            preserve_default=False,
        ),
    ]
