# Generated by Django 4.1.7 on 2023-04-17 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_remove_jobexperience_cv_jobexperience_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobexperience',
            name='user',
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='cv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_exp', to='cv.cv', verbose_name='Резюме'),
            preserve_default=False,
        ),
    ]
