# Generated by Django 4.1.7 on 2023-04-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_cv_created_at_cv_updated_at_jobexperience_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={'ordering': ['-updated_at']},
        ),
    ]
